# Generated by Django 4.1.7 on 2023-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timothy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('portfolio_image', models.ImageField(upload_to='images/')),
                ('percentage', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
