# Generated by Django 4.1.7 on 2023-03-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timothy', '0003_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='name',
        ),
    ]
